########################################### KANIKO TEMPLATE s######################################################
stages:
  - test
##################################################################################################################
before_script:
  - echo "CURRENT LOCATION - $PWD"
  - echo "SYSTEM INFO:"
  - cat /etc/os-release
  - cat /etc/hostname
##################################################################################################################

##################################################################################################################
TEST:
  stage: test
    #variables:
  #http_proxy: "http://localhost:5050"

  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]

  before_script:
    - |-
      ls -la
      echo ${PWD}
  - echo "${CI_REGISTRY_IMAGE}:test"
    - ls -la /kaniko/.docker

    script:
      - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
        --destination "${CI_REGISTRY_IMAGE}:test"
        --verbosity trace
      #--build-arg http_proxy=$https_proxy

##################################################################################################################
