########################################### KANIKO TEMPLATE s######################################################
stages:
  - test
##################################################################################################################
before_script:
  - echo "CURRENT LOCATION - $PWD"
  - echo "SYSTEM INFO:"
  - cat /etc/os-release
  - cat /etc/hostname
##################################################################################################################

##################################################################################################################
TEST:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]

  before_script:
    - |-
      ls -la
      echo ${PWD}

  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:test"
    #--destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
