##################################################################################################################
stages:
  - test
##################################################################################################################
before_script:
  - echo "CURRENT LOCATION - $PWD"
  - echo "SYSTEM INFO:"
  - cat /etc/os-release
  - cat /etc/hostname
##################################################################################################################

##################################################################################################################
BUILD:

  stage: test

  before_script:
    - |-
      ls -la
      echo ${PWD}

  script:
    - docker run hello-world

##################################################################################################################

