image:
  registry: registry.gitlab.com
  image: gitlab-org/gitlab-runner

imagePullPolicy: IfNotPresent

gitlabUrl: https://gitlab.huseynov.net/

runnerRegistrationToken: "eQsk2YsyBGJaAFd4iJs6"

terminationGracePeriodSeconds: 3600
concurrent: 30
checkInterval: 30
sessionServer:
  enabled: false

rbac:
  create: false
  rules: []
  clusterWideAccess: false
  serviceAccountName: gitlab
  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner

metrics:
  enabled: false
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false

service:
  enabled: false
  type: ClusterIP

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "docker:20.10.20"

  cache: {}
  builds: {}
  services: {}
  helpers: {}
  cloneUrl: https://gitlab.huseynov.net

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  privileged: false
  capabilities:
    drop: ["ALL"]

podSecurityContext:
  runAsUser: 100
  fsGroup: 65533

resources: {}

affinity: {}

nodeSelector: {}

tolerations: []

hostAliases: []

podAnnotations: {}

podLabels: {}

priorityClassName: ""

secrets: []

configMaps: {}

volumeMounts: []

volumes: []