apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitlab
  name: gitlab-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "pods/exec", "secrets", "configmaps", "pods/attach"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]